// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkzeppaonlelkdxraump.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtremVwcGFvbmxlbGtkeHJhdW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5ODQ0OTIsImV4cCI6MjA3MTU2MDQ5Mn0.7ubvHDhn5BR56YrK4g7BoCRz9K3ymvvjmEZzBAS8FAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});